# Generated by Django 3.0.4 on 2020-03-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200326_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphanage',
            name='mobileno',
            field=models.IntegerField(default=None),
        ),
    ]
