# Generated by Django 3.0.4 on 2020-03-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_orphanage_mobileno'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thing',
            name='timeofReceving',
            field=models.DateTimeField(default=None),
        ),
    ]
