# Generated by Django 3.0.4 on 2020-03-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200331_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='approval',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='thing',
            name='timeofReceving',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
