# Generated by Django 3.0.4 on 2020-03-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200331_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='approval',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='thing',
            name='timeofReceving',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
